name: 'Meson Format Action'
author: Totto16
description: 'Check if meson files are formatted correctly'
inputs:
  format-file:
    description: 'Path of format file'
    required: false
    default: ''
  only-git-files:
    description: 'Only check files, that are check into git'
    required: false
    default: 'true'
branding:
  icon: check-circle
  color: green
runs:
  using: 'composite'
  steps:
    - name: Install Node.Js
      uses: actions/setup-node@v6
      id: setup-js
      with:
        node-version: 24

    - name: Install Node Dependencies
      id: install-dependencies
      shell: bash
      run: |
        cd "${{github.action_path}}"
        npm ci --production

    # NOTE: meson has no dependencies, so --break-system-packages doesn't really break anything!
    ## TODO: install meson in javascript, so that multiple platforms are supported and so that it is not installed, if already present
    - name: Setup meson
      id: install-meson
      shell: bash
      run: |
        pip install meson --break-system-packages

    - name: Run checker
      shell: bash
      id: meson-format-checker
      env:
          INPUT_FORMAT-FILE: ${{ inputs.format-file }}
          INPUT_ONLY-GIT-FILES: ${{ inputs.only-git-files }}
      run: |
        node "${{github.action_path}}/index.js"
